D :=.

MatrixMult1Cpp:
	@g++ -o $(D)/$@ $(D)/MatrixMult1.cpp
	$(D)/$@

MatrixMult2Cpp:
	@g++ -o $(D)/$@ $(D)/MatrixMult2.cpp
	$(D)/$@

MatrixMult3Cpp:
	@g++ -o $(D)/$@ $(D)/MatrixMult3.cpp
	$(D)/$@


Concat1Cpp:
	@g++ -o $(D)/$@ $(D)/Concat1.cpp
	$(D)/$@

Concat2Cpp:
	@g++ -o $(D)/$@ $(D)/Concat2.cpp
	$(D)/$@

Concat3Cpp:
	@g++ -o $(D)/$@ $(D)/Concat3.cpp
	$(D)/$@


Regexp1Cpp:
	@g++ -o $(D)/$@ $(D)/Regexp1.cpp
	$(D)/$@

Regexp2Cpp:
	@g++ -o $(D)/$@ $(D)/Regexp2.cpp
	$(D)/$@

Regexp3Cpp:
	@g++ -o $(D)/$@ $(D)/Regexp3.cpp
	$(D)/$@

