D :=.

MATRIX_MULT_DATA:=../../data/matrix_mult/data.txt
CONCAT_DATA:=../../data/concat/data.txt
REGEXP_DATA:=../../data/regexp/data.txt

.PHONY: allPerl
.PHONY: MatrixMult1Perl MatrixMult2Perl MatrixMult3Perl
.PHONY: Concat1Perl Concat2Perl Concat3Perl
.PHONY: Regexp1Perl Regexp2Perl Regexp3Perl

allPerl: MatrixMult1Perl MatrixMult2Perl MatrixMult3Perl Concat1Perl Concat2Perl Concat3Perl Regexp1Perl Regexp2Perl Regexp3Perl

MatrixMult1Perl:
	perl $(D)/MatrixMult1.pl

MatrixMult2Perl:
	perl $(D)/MatrixMult2.pl

MatrixMult3Perl:
	perl $(D)/MatrixMult3.pl


Concat1Perl:
	perl $(D)/Concat1.pl

Concat2Perl:
	perl $(D)/Concat2.pl

Concat3Perl:
	perl $(D)/Concat3.pl


Regexp1Perl:
	perl $(D)/Regexp1.pl

Regexp2Perl:
	perl $(D)/Regexp2.pl

Regexp3Perl:
	perl $(D)/Regexp3.pl

